name: Get personal Information

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'

jobs:
  scrape_info:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-python@v4
        with: 
          python-version: "3.10"
      - name: Get Dependencies
        run: pip install -r requirements.txt
      - name: Run Script
        run: python script.py
      - name: Push to GitHub
        run: |
          git config --global user.email "vedang.bhagwat@outlook.com"
          git config --global user.name "vedangbhagwat"
          git add .
          git commit -m "Automated Update"
          git push
